# Generated by Django 5.0.4 on 2024-04-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemmodel',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
