# Generated by Django 5.0.4 on 2024-04-10 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemmodel',
            name='parent',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tree_menu.menuitemmodel'),
        ),
    ]
