# Generated by Django 5.0.4 on 2024-04-10 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0002_alter_menuitemmodel_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_go', to='tree_menu.menuitemmodel'),
        ),
    ]
