# Generated by Django 5.0.4 on 2024-04-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0003_alter_menuitemmodel_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemmodel',
            name='lvl',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
