# Generated by Django 5.0.4 on 2024-04-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0003_menuitemmodel_named_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemmodel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='menuitemmodel',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
