# Generated by Django 5.0.4 on 2024-04-16 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0005_alter_menuitemmodel_parent_alter_menuitemmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemmodel',
            name='lvl',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='menuitemmodel',
            name='named_url',
            field=models.SlugField(blank=True),
        ),
    ]
